name: Python application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.3"
    - name: Setup virtual environment and install dependencies
      run: |
        make setup-venv
        make install
    - name: Run tests with coverage
      run: |
        make test-dev
    - name: Run linting (non-blocking)
      run: |
        make lint || echo "Linting issues found - check logs above"
    - name: Upload coverage reports
      if: success() || failure()
      run: |
        echo "Coverage report generated in htmlcov/"
        if [ -f coverage.xml ]; then
          echo "Coverage XML report available"
        fi
